name = "aegis-app"
main = "server.ts"
compatibility_date = "2024-12-01"

[assets]
directory = "./ui"
binding = "ASSETS"
not_found_handling = "none"
run_worker_first = ["/*"]

[[d1_databases]]
binding = "DB"
database_name = "aegis-tickets"
database_id = "ba933637-7892-4e70-8f09-2aa76ebabf42"

[triggers]
crons = ["0 * * * *"]
